-- E-Learning Platform Database Schema

CREATE DATABASE IF NOT EXISTS `e-learning platform`;
USE `e-learning platform`;

-- Users Table
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) UNIQUE NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('student', 'instructor', 'admin', 'course_team', 'dept_head', 'data_analyst', 'office_manager') NOT NULL,
  `phone` VARCHAR(20),
  `address` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` BOOLEAN DEFAULT TRUE,
  INDEX idx_email (email),
  INDEX idx_role (role)
);

-- Courses Table
CREATE TABLE IF NOT EXISTS `courses` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `instructor_id` INT NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `status` ENUM('Draft', 'Ongoing', 'Completed') DEFAULT 'Draft',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `thumbnail` VARCHAR(255),
  FOREIGN KEY (instructor_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_instructor (instructor_id),
  INDEX idx_status (status)
);

-- Enrollments Table
CREATE TABLE IF NOT EXISTS `enrollments` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `progress` INT DEFAULT 0,
  `status` ENUM('Active', 'Completed', 'Dropped') DEFAULT 'Active',
  `enrolled_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `completed_at` DATETIME,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  UNIQUE KEY unique_enrollment (user_id, course_id),
  INDEX idx_user (user_id),
  INDEX idx_course (course_id)
);

-- Certificates Table
CREATE TABLE IF NOT EXISTS `certificates` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `issued_date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `certificate_number` VARCHAR(50) UNIQUE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  INDEX idx_user (user_id)
);

-- Submissions (Course Team Approvals) Table
CREATE TABLE IF NOT EXISTS `submissions` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `submitted_by` INT NOT NULL,
  `status` ENUM('Pending', 'Under Review', 'Approved', 'Rejected') DEFAULT 'Pending',
  `submitted_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `reviewed_at` DATETIME,
  `reviewed_by` INT,
  `notes` TEXT,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (submitted_by) REFERENCES users(id),
  FOREIGN KEY (reviewed_by) REFERENCES users(id),
  INDEX idx_status (status)
);

-- Analytics Table
CREATE TABLE IF NOT EXISTS `analytics` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT,
  `course_id` INT,
  `event_type` VARCHAR(50),
  `event_data` JSON,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  INDEX idx_event (event_type),
  INDEX idx_created (created_at)
);

-- Registrations (Office Manager) Table
CREATE TABLE IF NOT EXISTS `registrations` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `status` ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
  `payment_status` ENUM('Unpaid', 'Paid', 'Refunded') DEFAULT 'Unpaid',
  `amount` DECIMAL(10, 2),
  `registered_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `processed_at` DATETIME,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  INDEX idx_status (status),
  INDEX idx_payment (payment_status)
);

-- Department Faculty Table
CREATE TABLE IF NOT EXISTS `department_faculty` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `faculty_id` INT NOT NULL,
  `dept_head_id` INT NOT NULL,
  `average_rating` DECIMAL(3, 2),
  `courses_count` INT DEFAULT 0,
  `added_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (faculty_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (dept_head_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Insert demo users (20 records per role)
INSERT INTO `users` (`name`, `email`, `password`, `role`) VALUES
('Student Demo', 'student@demo', MD5('demo'), 'student'),
('Instructor Demo', 'instructor@demo', MD5('demo'), 'instructor'),
('Admin Demo', 'admin@demo', MD5('demo'), 'admin'),
('Course Team', 'course@demo', MD5('demo'), 'course_team'),
('Dept Head', 'head@demo', MD5('demo'), 'dept_head'),
('Data Analyst', 'analyst@demo', MD5('demo'), 'data_analyst'),
('Office Manager', 'office@demo', MD5('demo'), 'office_manager'),
-- Students (20 total)
('Ahmed Hassan', 'ahmed.hassan@student.com', MD5('pass123'), 'student'),
('Fatima Khan', 'fatima.khan@student.com', MD5('pass123'), 'student'),
('Ali Mohammad', 'ali.mohammad@student.com', MD5('pass123'), 'student'),
('Sara Ahmed', 'sara.ahmed@student.com', MD5('pass123'), 'student'),
('Omar Ibrahim', 'omar.ibrahim@student.com', MD5('pass123'), 'student'),
('Zainab Ali', 'zainab.ali@student.com', MD5('pass123'), 'student'),
('Hassan Karim', 'hassan.karim@student.com', MD5('pass123'), 'student'),
('Amira Abdullah', 'amira.abdullah@student.com', MD5('pass123'), 'student'),
('Mohammed Rashid', 'mohammed.rashid@student.com', MD5('pass123'), 'student'),
('Layla Hassan', 'layla.hassan@student.com', MD5('pass123'), 'student'),
('Karim Noor', 'karim.noor@student.com', MD5('pass123'), 'student'),
('Nadia Samir', 'nadia.samir@student.com', MD5('pass123'), 'student'),
('Tariq Ahmed', 'tariq.ahmed@student.com', MD5('pass123'), 'student'),
('Hana Rashid', 'hana.rashid@student.com', MD5('pass123'), 'student'),
('Samir Karim', 'samir.karim@student.com', MD5('pass123'), 'student'),
('Dina Hassan', 'dina.hassan@student.com', MD5('pass123'), 'student'),
('Rayan Malik', 'rayan.malik@student.com', MD5('pass123'), 'student'),
('Leila Noor', 'leila.noor@student.com', MD5('pass123'), 'student'),
('Yousuf Ahmed', 'yousuf.ahmed@student.com', MD5('pass123'), 'student'),
('Mona Salim', 'mona.salim@student.com', MD5('pass123'), 'student'),
-- Instructors (20 total)
('Dr. Ahmed Rahman', 'dr.ahmed.rahman@instructor.com', MD5('pass123'), 'instructor'),
('Prof. Nipa Chakraborty', 'prof.nipa@instructor.com', MD5('pass123'), 'instructor'),
('Mr. Karim Shaikh', 'mr.karim.shaikh@instructor.com', MD5('pass123'), 'instructor'),
('Dr. Salina Ahmed', 'dr.salina.ahmed@instructor.com', MD5('pass123'), 'instructor'),
('Prof. Hassan Yousuf', 'prof.hassan@instructor.com', MD5('pass123'), 'instructor'),
('Ms. Aisha Malik', 'ms.aisha.malik@instructor.com', MD5('pass123'), 'instructor'),
('Dr. Raza Khan', 'dr.raza.khan@instructor.com', MD5('pass123'), 'instructor'),
('Prof. Layla Hassan', 'prof.layla@instructor.com', MD5('pass123'), 'instructor'),
('Mr. Tariq Ibrahim', 'mr.tariq.ibrahim@instructor.com', MD5('pass123'), 'instructor'),
('Dr. Zainab Ali', 'dr.zainab.ali@instructor.com', MD5('pass123'), 'instructor'),
('Ms. Amira Abdullah', 'ms.amira.abdullah@instructor.com', MD5('pass123'), 'instructor'),
('Prof. Omar Rashid', 'prof.omar.rashid@instructor.com', MD5('pass123'), 'instructor'),
('Dr. Fatima Ahmed', 'dr.fatima.ahmed@instructor.com', MD5('pass123'), 'instructor'),
('Mr. Samir Hassan', 'mr.samir.hassan@instructor.com', MD5('pass123'), 'instructor'),
('Prof. Hana Noor', 'prof.hana.noor@instructor.com', MD5('pass123'), 'instructor'),
('Dr. Karim Salim', 'dr.karim.salim@instructor.com', MD5('pass123'), 'instructor'),
('Ms. Dina Malik', 'ms.dina.malik@instructor.com', MD5('pass123'), 'instructor'),
('Prof. Yousuf Ahmed', 'prof.yousuf.ahmed@instructor.com', MD5('pass123'), 'instructor'),
('Dr. Rayan Hassan', 'dr.rayan.hassan@instructor.com', MD5('pass123'), 'instructor'),
('Mr. Nasser Karim', 'mr.nasser.karim@instructor.com', MD5('pass123'), 'instructor'),
-- Admins (5 + 1 demo = 6 total, padding to 20)
('System Administrator', 'admin1@example.com', MD5('pass123'), 'admin'),
('Database Admin', 'admin2@example.com', MD5('pass123'), 'admin'),
('Platform Manager', 'admin3@example.com', MD5('pass123'), 'admin'),
('Support Admin', 'admin4@example.com', MD5('pass123'), 'admin'),
('Content Admin', 'admin5@example.com', MD5('pass123'), 'admin'),
('Security Admin', 'admin6@example.com', MD5('pass123'), 'admin'),
('Analytics Admin', 'admin7@example.com', MD5('pass123'), 'admin'),
('Finance Admin', 'admin8@example.com', MD5('pass123'), 'admin'),
('User Admin', 'admin9@example.com', MD5('pass123'), 'admin'),
('Course Admin', 'admin10@example.com', MD5('pass123'), 'admin'),
('Quality Admin', 'admin11@example.com', MD5('pass123'), 'admin'),
('Reports Admin', 'admin12@example.com', MD5('pass123'), 'admin'),
('System Monitor', 'admin13@example.com', MD5('pass123'), 'admin'),
('Backup Admin', 'admin14@example.com', MD5('pass123'), 'admin'),
-- Course Team (20 total)
('Marium Syed', 'marium.syed@courseteam.com', MD5('pass123'), 'course_team'),
('Khalid Hassan', 'khalid.hassan@courseteam.com', MD5('pass123'), 'course_team'),
('Yasmin Ahmed', 'yasmin.ahmed@courseteam.com', MD5('pass123'), 'course_team'),
('Ibrahim Malik', 'ibrahim.malik@courseteam.com', MD5('pass123'), 'course_team'),
('Sophia Khan', 'sophia.khan@courseteam.com', MD5('pass123'), 'course_team'),
('Hassan Ali', 'hassan.ali@courseteam.com', MD5('pass123'), 'course_team'),
('Noor Abdullah', 'noor.abdullah@courseteam.com', MD5('pass123'), 'course_team'),
('Adnan Rashid', 'adnan.rashid@courseteam.com', MD5('pass123'), 'course_team'),
('Leila Karim', 'leila.karim@courseteam.com', MD5('pass123'), 'course_team'),
('Rashid Hassan', 'rashid.hassan@courseteam.com', MD5('pass123'), 'course_team'),
('Amina Ahmed', 'amina.ahmed@courseteam.com', MD5('pass123'), 'course_team'),
('Faisal Ibrahim', 'faisal.ibrahim@courseteam.com', MD5('pass123'), 'course_team'),
('Huda Malik', 'huda.malik@courseteam.com', MD5('pass123'), 'course_team'),
('Karim Nasser', 'karim.nasser@courseteam.com', MD5('pass123'), 'course_team'),
('Mariam Hassan', 'mariam.hassan@courseteam.com', MD5('pass123'), 'course_team'),
('Tariq Salim', 'tariq.salim@courseteam.com', MD5('pass123'), 'course_team'),
('Rania Ahmed', 'rania.ahmed@courseteam.com', MD5('pass123'), 'course_team'),
('Saad Karim', 'saad.karim@courseteam.com', MD5('pass123'), 'course_team'),
('Nadia Hassan', 'nadia.hassan@courseteam.com', MD5('pass123'), 'course_team'),
('Zaki Abdullah', 'zaki.abdullah@courseteam.com', MD5('pass123'), 'course_team'),
-- Department Heads (20 total)
('Dr. Mohammad Hassan', 'dr.mohammad.hassan@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Amina Khan', 'prof.amina.khan@depthead.com', MD5('pass123'), 'dept_head'),
('Dr. Rashid Ahmed', 'dr.rashid.ahmed@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Leila Ibrahim', 'prof.leila.ibrahim@depthead.com', MD5('pass123'), 'dept_head'),
('Dr. Karim Malik', 'dr.karim.malik@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Noor Abdullah', 'prof.noor.abdullah@depthead.com', MD5('pass123'), 'dept_head'),
('Dr. Fatima Hassan', 'dr.fatima.hassan@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Yousuf Ahmed', 'prof.yousuf.ahmed@depthead.com', MD5('pass123'), 'dept_head'),
('Dr. Hana Rashid', 'dr.hana.rashid@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Samir Khan', 'prof.samir.khan@depthead.com', MD5('pass123'), 'dept_head'),
('Dr. Dina Ali', 'dr.dina.ali@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Tariq Hassan', 'prof.tariq.hassan@depthead.com', MD5('pass123'), 'dept_head'),
('Dr. Rayan Malik', 'dr.rayan.malik@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Layla Karim', 'prof.layla.karim@depthead.com', MD5('pass123'), 'dept_head'),
('Dr. Zainab Ahmed', 'dr.zainab.ahmed@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Adnan Hassan', 'prof.adnan.hassan@depthead.com', MD5('pass123'), 'dept_head'),
('Dr. Mona Abdullah', 'dr.mona.abdullah@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Nasser Malik', 'prof.nasser.malik@depthead.com', MD5('pass123'), 'dept_head'),
('Dr. Amira Khan', 'dr.amira.khan@depthead.com', MD5('pass123'), 'dept_head'),
('Prof. Hassan Rashid', 'prof.hassan.rashid@depthead.com', MD5('pass123'), 'dept_head'),
-- Data Analysts (20 total)
('Alex Morrison', 'alex.morrison@analyst.com', MD5('pass123'), 'data_analyst'),
('Maya Sharma', 'maya.sharma@analyst.com', MD5('pass123'), 'data_analyst'),
('Jordan Lee', 'jordan.lee@analyst.com', MD5('pass123'), 'data_analyst'),
('Priya Desai', 'priya.desai@analyst.com', MD5('pass123'), 'data_analyst'),
('Chris Taylor', 'chris.taylor@analyst.com', MD5('pass123'), 'data_analyst'),
('Isha Patel', 'isha.patel@analyst.com', MD5('pass123'), 'data_analyst'),
('Sam Chen', 'sam.chen@analyst.com', MD5('pass123'), 'data_analyst'),
('Aisha Rahman', 'aisha.rahman@analyst.com', MD5('pass123'), 'data_analyst'),
('David Martinez', 'david.martinez@analyst.com', MD5('pass123'), 'data_analyst'),
('Nora Singh', 'nora.singh@analyst.com', MD5('pass123'), 'data_analyst'),
('Lucas Garcia', 'lucas.garcia@analyst.com', MD5('pass123'), 'data_analyst'),
('Sofia Rossi', 'sofia.rossi@analyst.com', MD5('pass123'), 'data_analyst'),
('Oliver Kim', 'oliver.kim@analyst.com', MD5('pass123'), 'data_analyst'),
('Emma White', 'emma.white@analyst.com', MD5('pass123'), 'data_analyst'),
('Noah Johnson', 'noah.johnson@analyst.com', MD5('pass123'), 'data_analyst'),
('Lily Brown', 'lily.brown@analyst.com', MD5('pass123'), 'data_analyst'),
('Ethan Davis', 'ethan.davis@analyst.com', MD5('pass123'), 'data_analyst'),
('Ava Wilson', 'ava.wilson@analyst.com', MD5('pass123'), 'data_analyst'),
('Mason Moore', 'mason.moore@analyst.com', MD5('pass123'), 'data_analyst'),
('Isabella Jackson', 'isabella.jackson@analyst.com', MD5('pass123'), 'data_analyst'),
-- Office Managers (20 total)
('Patricia Johnson', 'patricia.johnson@officemanager.com', MD5('pass123'), 'office_manager'),
('Michael Brown', 'michael.brown@officemanager.com', MD5('pass123'), 'office_manager'),
('Jennifer Davis', 'jennifer.davis@officemanager.com', MD5('pass123'), 'office_manager'),
('Robert Miller', 'robert.miller@officemanager.com', MD5('pass123'), 'office_manager'),
('Linda Wilson', 'linda.wilson@officemanager.com', MD5('pass123'), 'office_manager'),
('James Moore', 'james.moore@officemanager.com', MD5('pass123'), 'office_manager'),
('Barbara Taylor', 'barbara.taylor@officemanager.com', MD5('pass123'), 'office_manager'),
('Richard Anderson', 'richard.anderson@officemanager.com', MD5('pass123'), 'office_manager'),
('Susan Thomas', 'susan.thomas@officemanager.com', MD5('pass123'), 'office_manager'),
('Charles Jackson', 'charles.jackson@officemanager.com', MD5('pass123'), 'office_manager'),
('Jessica Martin', 'jessica.martin@officemanager.com', MD5('pass123'), 'office_manager'),
('Christopher Harris', 'christopher.harris@officemanager.com', MD5('pass123'), 'office_manager'),
('Sarah Thompson', 'sarah.thompson@officemanager.com', MD5('pass123'), 'office_manager'),
('Daniel White', 'daniel.white@officemanager.com', MD5('pass123'), 'office_manager'),
('Karen Martinez', 'karen.martinez@officemanager.com', MD5('pass123'), 'office_manager'),
('Matthew Robinson', 'matthew.robinson@officemanager.com', MD5('pass123'), 'office_manager'),
('Lisa Clark', 'lisa.clark@officemanager.com', MD5('pass123'), 'office_manager'),
('Mark Rodriguez', 'mark.rodriguez@officemanager.com', MD5('pass123'), 'office_manager'),
('Nancy Lewis', 'nancy.lewis@officemanager.com', MD5('pass123'), 'office_manager'),
('Steven Lee', 'steven.lee@officemanager.com', MD5('pass123'), 'office_manager');

-- Insert sample courses (20 records)
INSERT INTO `courses` (`title`, `description`, `instructor_id`, `category`, `status`) VALUES
('AI Basics', 'Introduction to Artificial Intelligence', 2, 'AI', 'Ongoing'),
('Database Systems', 'Learn SQL and NoSQL databases', 2, 'DB', 'Completed'),
('Web Development', 'Full stack web development course', 2, 'IT', 'Ongoing'),
('Python Programming', 'Master Python for beginners and advanced users', 9, 'Programming', 'Ongoing'),
('JavaScript Fundamentals', 'Learn JavaScript from basics to advanced', 10, 'Programming', 'Ongoing'),
('Machine Learning 101', 'Introduction to Machine Learning concepts', 11, 'AI', 'Ongoing'),
('Data Science Essentials', 'Essential skills for data science professionals', 12, 'Data Science', 'Ongoing'),
('Cloud Computing with AWS', 'Deploy applications on AWS cloud platform', 13, 'Cloud', 'Ongoing'),
('Digital Marketing Strategy', 'Complete guide to digital marketing', 14, 'Marketing', 'Completed'),
('UI/UX Design Principles', 'Master design principles and tools', 15, 'Design', 'Ongoing'),
('React.js Advanced', 'Build advanced applications with React', 16, 'Programming', 'Ongoing'),
('Mobile App Development', 'Develop iOS and Android applications', 17, 'Mobile', 'Ongoing'),
('Cybersecurity Fundamentals', 'Protect systems and data from threats', 18, 'Security', 'Draft'),
('DevOps Essentials', 'Master continuous integration and deployment', 19, 'DevOps', 'Ongoing'),
('Blockchain Technology', 'Understanding blockchain and cryptocurrencies', 20, 'Blockchain', 'Ongoing'),
('Advanced SQL', 'Complex queries and database optimization', 9, 'DB', 'Ongoing'),
('GraphQL API Development', 'Build modern APIs with GraphQL', 10, 'API', 'Draft'),
('Docker Containerization', 'Master Docker for application deployment', 11, 'DevOps', 'Ongoing'),
('Business Analytics', 'Data-driven business decision making', 12, 'Analytics', 'Completed'),
('Leadership Skills for Managers', 'Effective leadership and team management', 13, 'Management', 'Ongoing');

-- Insert enrollments (40 records - mix of students)
INSERT INTO `enrollments` (`user_id`, `course_id`, `progress`, `status`) VALUES
(8, 1, 85, 'Active'), (8, 2, 100, 'Completed'), (8, 3, 45, 'Active'),
(9, 1, 60, 'Active'), (9, 4, 75, 'Active'), (9, 5, 30, 'Active'),
(10, 2, 100, 'Completed'), (10, 6, 55, 'Active'), (10, 7, 40, 'Active'),
(11, 3, 70, 'Active'), (11, 8, 85, 'Active'), (11, 9, 0, 'Dropped'),
(12, 1, 90, 'Active'), (12, 10, 65, 'Active'), (12, 11, 50, 'Active'),
(13, 4, 100, 'Completed'), (13, 12, 75, 'Active'), (13, 13, 25, 'Active'),
(14, 2, 80, 'Active'), (14, 6, 60, 'Active'), (14, 14, 40, 'Active'),
(15, 5, 100, 'Completed'), (15, 7, 85, 'Active'), (15, 15, 50, 'Active'),
(16, 8, 70, 'Active'), (16, 9, 55, 'Active'), (16, 16, 30, 'Active'),
(17, 10, 65, 'Active'), (17, 11, 75, 'Active'), (17, 17, 40, 'Active'),
(18, 3, 100, 'Completed'), (18, 12, 85, 'Active'), (18, 18, 60, 'Active'),
(19, 1, 55, 'Active'), (19, 14, 70, 'Active'), (19, 19, 45, 'Active'),
(20, 4, 80, 'Active'), (20, 15, 65, 'Active'), (20, 20, 50, 'Active'),
(27, 2, 100, 'Completed'), (27, 6, 75, 'Active'), (27, 7, 40, 'Active');

-- Insert certificates (15 records)
INSERT INTO `certificates` (`user_id`, `course_id`, `certificate_number`) VALUES
(8, 2, 'CERT-8-2-20251201000001'),
(10, 2, 'CERT-10-2-20251201000002'),
(13, 4, 'CERT-13-4-20251201000003'),
(15, 5, 'CERT-15-5-20251201000004'),
(18, 3, 'CERT-18-3-20251201000005'),
(12, 1, 'CERT-12-1-20251201000006'),
(14, 2, 'CERT-14-2-20251201000007'),
(16, 8, 'CERT-16-8-20251201000008'),
(20, 4, 'CERT-20-4-20251201000009'),
(9, 1, 'CERT-9-1-20251201000010'),
(11, 2, 'CERT-11-2-20251201000011'),
(17, 3, 'CERT-17-3-20251201000012'),
(19, 1, 'CERT-19-1-20251201000013'),
(8, 1, 'CERT-8-1-20251201000014'),
(27, 2, 'CERT-27-2-20251201000015');

-- Insert submissions (20 records)
INSERT INTO `submissions` (`course_id`, `submitted_by`, `status`, `notes`) VALUES
(1, 9, 'Approved', 'Great course structure'),
(2, 10, 'Approved', 'Well organized content'),
(3, 11, 'Pending', NULL),
(4, 12, 'Under Review', 'Reviewing curriculum'),
(5, 13, 'Approved', 'Excellent material'),
(6, 14, 'Pending', NULL),
(7, 15, 'Approved', 'Good learning objectives'),
(8, 16, 'Rejected', 'Needs more examples'),
(9, 17, 'Approved', 'Professional content'),
(10, 18, 'Pending', NULL),
(11, 19, 'Under Review', 'Checking assessments'),
(12, 20, 'Approved', 'Well designed'),
(13, 9, 'Pending', NULL),
(14, 10, 'Approved', 'Comprehensive course'),
(15, 11, 'Under Review', 'Verifying sources'),
(16, 12, 'Approved', 'Excellent queries'),
(17, 13, 'Rejected', 'Missing documentation'),
(18, 14, 'Pending', NULL),
(19, 15, 'Approved', 'Great content'),
(20, 16, 'Under Review', 'Final review');

-- Insert analytics events (30 records)
INSERT INTO `analytics` (`user_id`, `course_id`, `event_type`, `event_data`) VALUES
(8, 1, 'course_viewed', '{"duration": 1800}'),
(8, 2, 'course_completed', '{"score": 92}'),
(9, 1, 'assignment_submitted', '{"grade": 85}'),
(9, 4, 'quiz_taken', '{"score": 78}'),
(10, 2, 'course_completed', '{"score": 95}'),
(10, 6, 'lesson_viewed', '{"duration": 2400}'),
(11, 3, 'assignment_submitted', '{"grade": 88}'),
(11, 8, 'course_viewed', '{"duration": 1500}'),
(12, 1, 'quiz_taken', '{"score": 91}'),
(12, 10, 'lesson_viewed', '{"duration": 2000}'),
(13, 4, 'course_completed', '{"score": 98}'),
(13, 12, 'assignment_submitted', '{"grade": 90}'),
(14, 2, 'course_viewed', '{"duration": 1200}'),
(14, 6, 'quiz_taken', '{"score": 80}'),
(15, 5, 'course_completed', '{"score": 94}'),
(15, 7, 'lesson_viewed', '{"duration": 1800}'),
(16, 8, 'assignment_submitted', '{"grade": 82}'),
(16, 9, 'course_viewed', '{"duration": 2100}'),
(17, 10, 'quiz_taken', '{"score": 87}'),
(17, 11, 'lesson_viewed', '{"duration": 1600}'),
(18, 3, 'course_completed', '{"score": 89}'),
(18, 12, 'assignment_submitted', '{"grade": 85}'),
(19, 1, 'course_viewed', '{"duration": 900}'),
(19, 14, 'quiz_taken', '{"score": 79}'),
(20, 4, 'lesson_viewed', '{"duration": 1700}'),
(20, 15, 'assignment_submitted', '{"grade": 81}'),
(27, 2, 'course_completed', '{"score": 96}'),
(27, 6, 'quiz_taken', '{"score": 88}'),
(9, 5, 'course_viewed', '{"duration": 1400}'),
(11, 7, 'assignment_submitted', '{"grade": 86}');

-- Insert registrations (20 records)
INSERT INTO `registrations` (`user_id`, `course_id`, `status`, `payment_status`, `amount`) VALUES
(8, 1, 'Approved', 'Paid', 99.99),
(9, 1, 'Approved', 'Paid', 99.99),
(10, 2, 'Approved', 'Paid', 79.99),
(11, 3, 'Approved', 'Paid', 129.99),
(12, 1, 'Approved', 'Paid', 99.99),
(13, 4, 'Approved', 'Paid', 119.99),
(14, 2, 'Pending', 'Unpaid', 79.99),
(15, 5, 'Approved', 'Paid', 99.99),
(16, 8, 'Approved', 'Paid', 149.99),
(17, 10, 'Approved', 'Paid', 109.99),
(18, 3, 'Approved', 'Paid', 129.99),
(19, 1, 'Pending', 'Unpaid', 99.99),
(20, 4, 'Approved', 'Paid', 119.99),
(8, 6, 'Approved', 'Paid', 89.99),
(9, 12, 'Approved', 'Paid', 99.99),
(10, 7, 'Pending', 'Unpaid', 109.99),
(11, 13, 'Rejected', 'Unpaid', 139.99),
(12, 15, 'Approved', 'Paid', 99.99),
(13, 18, 'Pending', 'Unpaid', 119.99),
(14, 20, 'Approved', 'Paid', 99.99);

-- Insert department faculty relationships (15 records)
INSERT INTO `department_faculty` (`faculty_id`, `dept_head_id`, `average_rating`, `courses_count`) VALUES
(9, 56, 4.5, 4),
(10, 56, 4.7, 3),
(11, 57, 4.3, 5),
(12, 57, 4.8, 2),
(13, 58, 4.6, 4),
(14, 58, 4.4, 3),
(15, 59, 4.9, 2),
(16, 59, 4.2, 4),
(17, 60, 4.7, 3),
(18, 60, 4.5, 4),
(19, 61, 4.8, 2),
(20, 61, 4.3, 5),
(9, 62, 4.6, 3),
(10, 62, 4.4, 4),
(11, 63, 4.7, 3);
